---

- name: Create file
  file:
    path: madu/
    state: directory

- name: Copy docker-compose
  template:
    src: ../templates/docker-compose.yml
    dest: madu/docker-compose.yml

- name: Docker login
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: Run docker-compose
  docker_compose:
    project_src: madu/
