- name: 'install python2'
  become: true
  raw:  apt update && apt-get -y install python
  tags: ["install"]

- name: Gather facts
  setup:

- name: install packages
  become: true
  apt:
    pkg:
      - python-setuptools
      - python-pip
      - docker-compose
    state: present
    update_cache: yes

# Install PIP Dependencies
- name: Install pip dependencies
  pip:
    name:
      - docker
